# ver_settings.py
# Copyright (C) 2022 CESNET z. s. p. o.
# Author(s): Daniel Kříž <xkrizd01@vutbr.cz>

SETTINGS = {
    "default" : { # The default setting of verification
        "DMA_PORTS"           : "2",
        "MVB_UP_ITEMS"        : "2",
        "MFB_UP_REGIONS"      : "2",
        "MFB_UP_REG_SIZE"     : "1",
        "MFB_UP_BLOCK_SIZE"   : "8",
        "MFB_UP_ITEM_WIDTH"   : "32",
        "MVB_DOWN_ITEMS"      : "2",
        "MFB_DOWN_REGIONS"    : "2",
        "MFB_DOWN_REG_SIZE"   : "1",
        "MFB_DOWN_BLOCK_SIZE" : "8",
        "MFB_DOWN_ITEM_WIDTH" : "32",
        "ENDPOINT_TYPE"       : "\\\"P_TILE\\\"",
        "DEVICE"              : "\\\"STRATIX10\\\"",
        "CLK_PERIOD"          : "2.22222222ns",
    },
    "s10_256_port" : {
        "DMA_PORTS"            : "1",
        "MVB_UP_ITEMS"         : "1",
        "MFB_UP_REGIONS"       : "1",
        "MFB_UP_REG_SIZE"      : "1",
        "MFB_UP_BLOCK_SIZE"    : "8",
        "MFB_UP_ITEM_WIDTH"    : "32",
        "MVB_DOWN_ITEMS"       : "1",
        "MFB_DOWN_REGIONS"     : "1",
        "MFB_DOWN_REG_SIZE"    : "1",
        "MFB_DOWN_BLOCK_SIZE"  : "8",
        "MFB_DOWN_ITEM_WIDTH"  : "32",
        "ENDPOINT_TYPE"        : "\\\"P_TILE\\\"",
        "DEVICE"               : "\\\"STRATIX10\\\"",
    },
    "agilex_1_port_300mhz" : {
        "DMA_PORTS"            : "1",
        "MVB_UP_ITEMS"         : "2",
        "MFB_UP_REGIONS"       : "2",
        "MFB_UP_REG_SIZE"      : "1",
        "MFB_UP_BLOCK_SIZE"    : "8",
        "MFB_UP_ITEM_WIDTH"    : "32",
        "MVB_DOWN_ITEMS"       : "2",
        "MFB_DOWN_REGIONS"     : "2",
        "MFB_DOWN_REG_SIZE"    : "1",
        "MFB_DOWN_BLOCK_SIZE"  : "8",
        "MFB_DOWN_ITEM_WIDTH"  : "32",
        "ENDPOINT_TYPE"        : "\\\"R_TILE\\\"",
        "DEVICE"               : "\\\"AGILEX\\\"",
        "CLK_PERIOD"           : "3.33333333ns",
    },
    "agilex_1_port_500mhz" : {
        "DMA_PORTS"            : "1",
        "MVB_UP_ITEMS"         : "2",
        "MFB_UP_REGIONS"       : "2",
        "MFB_UP_REG_SIZE"      : "1",
        "MFB_UP_BLOCK_SIZE"    : "8",
        "MFB_UP_ITEM_WIDTH"    : "32",
        "MVB_DOWN_ITEMS"       : "2",
        "MFB_DOWN_REGIONS"     : "2",
        "MFB_DOWN_REG_SIZE"    : "1",
        "MFB_DOWN_BLOCK_SIZE"  : "8",
        "MFB_DOWN_ITEM_WIDTH"  : "32",
        "ENDPOINT_TYPE"        : "\\\"R_TILE\\\"",
        "DEVICE"               : "\\\"AGILEX\\\"",
        "CLK_PERIOD"           : "2ns",
    },
    "agilex_2_ports_300mhz" : {
        "DMA_PORTS"            : "2",
        "MVB_UP_ITEMS"         : "2",
        "MFB_UP_REGIONS"       : "2",
        "MFB_UP_REG_SIZE"      : "1",
        "MFB_UP_BLOCK_SIZE"    : "8",
        "MFB_UP_ITEM_WIDTH"    : "32",
        "MVB_DOWN_ITEMS"       : "2",
        "MFB_DOWN_REGIONS"     : "2",
        "MFB_DOWN_REG_SIZE"    : "1",
        "MFB_DOWN_BLOCK_SIZE"  : "8",
        "MFB_DOWN_ITEM_WIDTH"  : "32",
        "ENDPOINT_TYPE"        : "\\\"R_TILE\\\"",
        "DEVICE"               : "\\\"AGILEX\\\"",
        "CLK_PERIOD"           : "3.33333333ns",
    },
    "agilex_2_ports_500mhz" : {
        "DMA_PORTS"            : "2",
        "MVB_UP_ITEMS"         : "2",
        "MFB_UP_REGIONS"       : "2",
        "MFB_UP_REG_SIZE"      : "1",
        "MFB_UP_BLOCK_SIZE"    : "8",
        "MFB_UP_ITEM_WIDTH"    : "32",
        "MVB_DOWN_ITEMS"       : "2",
        "MFB_DOWN_REGIONS"     : "2",
        "MFB_DOWN_REG_SIZE"    : "1",
        "MFB_DOWN_BLOCK_SIZE"  : "8",
        "MFB_DOWN_ITEM_WIDTH"  : "32",
        "ENDPOINT_TYPE"        : "\\\"R_TILE\\\"",
        "DEVICE"               : "\\\"AGILEX\\\"",
        "CLK_PERIOD"           : "2ns",
    },
    "_combinations_" : (  
    (), # Works the same as '("default",),' as the "default" is applied in every combination
    ("s10_256_port",),
    ("agilex_1_port_300mhz",),
    ("agilex_1_port_500mhz",),
    ("agilex_2_ports_300mhz",),
    ("agilex_2_ports_500mhz",),
    ),
}