image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - apk add -U unzip curl
  - pip install -U sphinx
  - pip install -U sphinx-rtd-theme
  - curl --location --output artifacts.zip "https://gitlab.liberouter.org/api/v4/projects/107/jobs/artifacts/main/download?job=run&private_token=$SPHINXVHDL_API_KEY"
  - unzip artifacts.zip
  - pip install dist/*.whl
  - sphinx-build -b html doc/source/ public
  artifacts:
    paths:
    - public
  only:
  - devel
