# Makefile: Makefile to compile MFB Frame Masker
# Copyright (C) 2023 CESNET
# Author: Yaroslav Marushchenko <xmarus09@stud.fit.vutbr.cz>

TOP_LEVEL_ENT=MFB_FRAME_MASKER

.PHONY: all
all: comp

include ../../../../../build/Makefile
